apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-java-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: hello-java-app

  template:
    metadata:
      labels:
        app: hello-java-app

    spec:
      containers:
      - name: hello-java-app
        image: hello-java-app:latest

        ports:
        - containerPort: 8080
